import type { APIRoute } from 'astro';
import { getCorsHeaders, corsOptions } from '../../../lib/cors';

export const prerender = false;

export const OPTIONS: APIRoute = ({ request }) => corsOptions(request);

/**
 * POST /api/license/redeem
 * Allows a user to claim a license key with their current account email.
 * The key is proof of payment — if valid, it gets re-associated to the requesting email.
 * This solves the case where the Stripe payment email differs from the PATAPIM account email.
 */
export const POST: APIRoute = async (context) => {
  const env = context.locals.runtime.env;
  const cors = getCorsHeaders(context.request);

  let body: { email?: string; licenseKey?: string };
  try {
    body = await context.request.json();
  } catch {
    return new Response(JSON.stringify({ valid: false, error: 'Invalid JSON' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  const { email, licenseKey } = body;
  if (!email || !licenseKey) {
    return new Response(JSON.stringify({ valid: false, error: 'Email and licenseKey are required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  const kv = env.LICENSES;

  // Check if this key was already redeemed/transferred to a different account
  const alreadyRedeemed = await kv.get(`redeemed:${licenseKey}`);
  if (alreadyRedeemed && alreadyRedeemed !== email) {
    return new Response(JSON.stringify({
      valid: false,
      error: 'This license key has already been redeemed by another account',
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Look up the key — it must exist (generated by Stripe webhook or admin)
  const originalEmail = await kv.get(`key:${licenseKey}`);
  if (!originalEmail) {
    return new Response(JSON.stringify({ valid: false, error: 'License key not found' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Load the license record from the original email
  const raw = await kv.get(`license:${originalEmail}`);
  if (!raw) {
    return new Response(JSON.stringify({ valid: false, error: 'License data not found for this key' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  const license = JSON.parse(raw);

  // Prevent re-transfer: if this license was already transferred to someone else, reject
  if (license.status === 'transferred') {
    return new Response(JSON.stringify({
      valid: false,
      error: 'This license key has already been redeemed by another account',
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Verify the key matches the license record
  if (license.licenseKey !== licenseKey) {
    return new Response(JSON.stringify({ valid: false, error: 'License key mismatch' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Check status is valid
  const validStatuses = ['active', 'trialing'];
  const isCanceledButActive = license.status === 'canceled'
    && license.expiresAt && new Date(license.expiresAt) > new Date();

  if (!validStatuses.includes(license.status) && !isCanceledButActive) {
    return new Response(JSON.stringify({
      valid: false,
      error: `License is ${license.status}`,
      plan: license.plan,
      status: license.status,
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // If the email already matches, just return success (no re-association needed)
  if (originalEmail === email) {
    return new Response(JSON.stringify({
      valid: true,
      plan: license.plan,
      status: license.status,
      expiresAt: license.expiresAt,
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Re-associate the license to the new email
  const updatedLicense = { ...license, email };

  // Write new license record for the claiming email
  await kv.put(`license:${email}`, JSON.stringify(updatedLicense));

  // Update key reverse lookup to point to the new email
  await kv.put(`key:${licenseKey}`, email);

  // Update user record if the new email has a Google ID
  const googleId = await kv.get(`user-email:${email}`);
  if (googleId) {
    const userRaw = await kv.get(`user:${googleId}`);
    if (userRaw) {
      const user = JSON.parse(userRaw);
      user.licenseKey = licenseKey;
      user.plan = license.plan;
      await kv.put(`user:${googleId}`, JSON.stringify(user));
    }
  }

  // Mark key as redeemed so it can't be transferred again
  await kv.put(`redeemed:${licenseKey}`, email);

  // Keep the old license record but mark it as transferred
  license.status = 'transferred';
  license.transferredTo = email;
  license.transferredAt = new Date().toISOString();
  await kv.put(`license:${originalEmail}`, JSON.stringify(license));

  return new Response(JSON.stringify({
    valid: true,
    plan: updatedLicense.plan,
    status: updatedLicense.status,
    expiresAt: updatedLicense.expiresAt,
  }), {
    status: 200,
    headers: { 'Content-Type': 'application/json', ...cors },
  });
};
