import type { APIRoute } from 'astro';
import { getCorsHeaders, corsOptions } from '../../../lib/cors';
import { getUserFromRequestOrDeviceToken } from '../../../lib/auth';

export const prerender = false;

export const OPTIONS: APIRoute = ({ request }) => corsOptions(request);

/**
 * POST /api/license/redeem
 * Allows a user to claim a license key with their current account email.
 * The key is proof of payment — if valid, it gets re-associated to the requesting email.
 * This solves the case where the Stripe payment email differs from the PATAPIM account email.
 */
export const POST: APIRoute = async (context) => {
  const env = context.locals.runtime.env;
  const cors = getCorsHeaders(context.request);

  let body: { email?: string; licenseKey?: string };
  try {
    body = await context.request.json();
  } catch {
    return new Response(JSON.stringify({ valid: false, error: 'Invalid JSON' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Target account email to claim the key onto, plus the key itself — both from
  // the body (the desktop app passes its account email).
  const email = (body.email || '').trim();
  const { licenseKey } = body;
  if (!email || !licenseKey) {
    return new Response(JSON.stringify({ valid: false, error: 'Email and licenseKey are required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // SECURITY (BE-2, backward-compatible): just *validating* a key that already
  // belongs to `email` is harmless and stays unauthenticated, so existing app
  // clients keep working. But TRANSFERRING a key to a DIFFERENT email is the
  // account-takeover vector — that path (below) requires authentication AND
  // that the caller is claiming the key onto their OWN account. This closes the
  // "leaked key -> transfer to attacker, lock out owner" attack without
  // breaking installed apps that don't yet send a token. See SECURITY_FINDINGS.

  const kv = env.LICENSES;

  // Check if this key was already redeemed/transferred to a different account
  const alreadyRedeemed = await kv.get(`redeemed:${licenseKey}`);
  if (alreadyRedeemed && alreadyRedeemed !== email) {
    return new Response(JSON.stringify({
      valid: false,
      error: 'This license key has already been redeemed by another account',
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Look up the key — it must exist (generated by Stripe webhook or admin)
  const originalEmail = await kv.get(`key:${licenseKey}`);
  if (!originalEmail) {
    return new Response(JSON.stringify({ valid: false, error: 'License key not found' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Load the license record from the original email
  const raw = await kv.get(`license:${originalEmail}`);
  if (!raw) {
    return new Response(JSON.stringify({ valid: false, error: 'License data not found for this key' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  const license = JSON.parse(raw);

  // Prevent re-transfer: if this license was already transferred to someone else, reject
  if (license.status === 'transferred') {
    return new Response(JSON.stringify({
      valid: false,
      error: 'This license key has already been redeemed by another account',
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Verify the key matches the license record
  if (license.licenseKey !== licenseKey) {
    return new Response(JSON.stringify({ valid: false, error: 'License key mismatch' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // Check status is valid
  const validStatuses = ['active', 'trialing'];
  const isCanceledButActive = license.status === 'canceled'
    && license.expiresAt && new Date(license.expiresAt) > new Date();

  if (!validStatuses.includes(license.status) && !isCanceledButActive) {
    return new Response(JSON.stringify({
      valid: false,
      error: `License is ${license.status}`,
      plan: license.plan,
      status: license.status,
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // If the email already matches, just return success (no re-association needed)
  if (originalEmail === email) {
    return new Response(JSON.stringify({
      valid: true,
      plan: license.plan,
      status: license.status,
      expiresAt: license.expiresAt,
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...cors },
    });
  }

  // --- Transfer path: re-associating to a DIFFERENT email. This is the
  // takeover-sensitive operation, so require authentication and that the
  // authenticated caller is claiming the key onto their OWN account. ---
  const authedUser = await getUserFromRequestOrDeviceToken(
    env.SESSIONS,
    env.LICENSES,
    context.request,
  );
  if (!authedUser || authedUser.email.trim().toLowerCase() !== email.toLowerCase()) {
    return new Response(JSON.stringify({
      valid: false,
      error: 'Sign in with this account to claim a key bought under a different email',
    }), { status: 401, headers: { 'Content-Type': 'application/json', ...cors } });
  }

  // Re-associate the license to the new email
  const updatedLicense = { ...license, email };

  // Write new license record for the claiming email
  await kv.put(`license:${email}`, JSON.stringify(updatedLicense));

  // Update key reverse lookup to point to the new email
  await kv.put(`key:${licenseKey}`, email);

  // Update user record if the new email has a Google ID
  const googleId = await kv.get(`user-email:${email}`);
  if (googleId) {
    const userRaw = await kv.get(`user:${googleId}`);
    if (userRaw) {
      const user = JSON.parse(userRaw);
      user.licenseKey = licenseKey;
      user.plan = license.plan;
      await kv.put(`user:${googleId}`, JSON.stringify(user));
    }
  }

  // Mark key as redeemed so it can't be transferred again
  await kv.put(`redeemed:${licenseKey}`, email);

  // Keep the old license record but mark it as transferred
  license.status = 'transferred';
  license.transferredTo = email;
  license.transferredAt = new Date().toISOString();
  await kv.put(`license:${originalEmail}`, JSON.stringify(license));

  return new Response(JSON.stringify({
    valid: true,
    plan: updatedLicense.plan,
    status: updatedLicense.status,
    expiresAt: updatedLicense.expiresAt,
  }), {
    status: 200,
    headers: { 'Content-Type': 'application/json', ...cors },
  });
};
